#!/usr/bin/env ruby
require "git_plist"

data            = STDIN.read.force_encoding("ASCII-8BIT")
format, result  = GitPlist.clean(data)

if format == :unknown
  printf "%s", result
  exit
end

puts JSON.pretty_generate(result)
